In [1]:
import numpy as np
class lin_reg:
    def fit(self, X, y):
        X_add1 = np.column_stack((np.ones(X.shape[0]),X))
        self.theta = np.linalg.pinv(X_add1.T.dot(X_add1)).dot(X_add1.T).dot(y)
        self.intercept = self.theta[0]
        self.coef = self.theta[1:]
        return self
    def predict(self, X):
        new_matrix = np.repeat(self.coef, X.shape[0], axis = 1).T.dot(X.T) + self.intercept
        return new_matrix[0].T.reshape((X.shape[0],1))
    

In [2]:
X1 = 2 * np.random.rand(100, 1)
X2 = 3 * np.random.rand(100, 1)
X3 = 3 * np.random.rand(100, 1)

X = np.column_stack((X2,X3))
X = np.column_stack((X1,X))
y = 4 + 3 * X1 + 2*X2+ 0.256*X3 + np.random.randn(100, 1)

In [3]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X,y)
lr.intercept_, lr.coef_

(array([4.39865867]), array([[2.79192448, 2.01753934, 0.21641422]]))

In [4]:
lr.predict(X)[:5]

array([[14.4181379 ],
       [11.29049708],
       [ 8.73765482],
       [ 6.99559925],
       [12.69255075]])

In [5]:
myLr = lin_reg()
myLr.fit(X,y)

In [9]:
myLr.intercept,myLr.coef

(array([4.39865867]), array([[2.79192448],
        [2.01753934],
        [0.21641422]]))

In [12]:
myLr.predict(X)[:5]

array([[14.4181379 ],
       [11.29049708],
       [ 8.73765482],
       [ 6.99559925],
       [12.69255075]])

In [13]:
y[:5]

array([[15.10333682],
       [ 8.75577159],
       [ 8.27561064],
       [ 8.85718829],
       [11.70443013]])

Regression with r2 regularization

In [14]:
class myRidge:
    def __init__(self,alpha):
        self.alpha = alpha
    def fit(self, X, y):
        X_add1 = X
        #X_add1 = np.column_stack((np.ones(X.shape[0]),X))
        self.theta = np.linalg.pinv(X_add1.T.dot(X_add1)+self.alpha*np.identity(X_add1.shape[1])).dot(X_add1.T).dot(y)
        self.intercept = self.theta[0]
        self.coef = self.theta[1:]
        return self
    def predict(self, X):
        new_matrix = np.repeat(self.coef, X.shape[0], axis = 1).T.dot(X.T) + self.intercept
        return new_matrix[0].T.reshape((X.shape[0],1))
    

In [15]:
myRi = myRidge(alpha=1)
myRi.fit(X,y)
myRi.intercept, myRi.coef

(array([4.11194643]), array([[2.86102465],
        [1.04108466]]))

In [16]:
from sklearn.linear_model import Ridge
rid = Ridge(alpha=1, fit_intercept = False)
rid.fit(X,y)
rid.intercept_, rid.coef_

(0.0, array([[4.11194643, 2.86102465, 1.04108466]]))